In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data = np.random.randn(4,3)

In [4]:
data

array([[-1.17565288,  1.25985945,  1.3367748 ],
       [-0.7120347 ,  0.657909  ,  0.38430577],
       [-1.77417494,  1.78738441,  0.39106521],
       [-1.40256861,  0.43249799, -0.62445794]])

In [5]:
data_frame = pd.DataFrame(data)

In [6]:
data_frame

          0         1         2
0 -1.175653  1.259859  1.336775
1 -0.712035  0.657909  0.384306
2 -1.774175  1.787384  0.391065
3 -1.402569  0.432498 -0.624458

In [7]:
type(data_frame)

pandas.DataFrame

In [8]:
type(data_frame[0])

pandas.Series

In [9]:
new_data_frame = pd.DataFrame(data, index = ["Serkan", "Ahmet", "Mısra", "İpek"], columns = ["Age", "Salary", "Seniority"])

In [10]:
new_data_frame

             Age    Salary  Seniority
Serkan -1.175653  1.259859   1.336775
Ahmet  -0.712035  0.657909   0.384306
Mısra  -1.774175  1.787384   0.391065
İpek   -1.402569  0.432498  -0.624458

In [11]:
new_data_frame[["Age","Salary"]]

             Age    Salary
Serkan -1.175653  1.259859
Ahmet  -0.712035  0.657909
Mısra  -1.774175  1.787384
İpek   -1.402569  0.432498

In [12]:
new_data_frame.loc["Serkan"]

Age         -1.175653
Salary       1.259859
Seniority    1.336775
Name: Serkan, dtype: float64

In [13]:
new_data_frame.iloc[2]

Age         -1.774175
Salary       1.787384
Seniority    0.391065
Name: Mısra, dtype: float64

In [14]:
new_data_frame.iloc[:,1]

Serkan    1.259859
Ahmet     0.657909
Mısra     1.787384
İpek      0.432498
Name: Salary, dtype: float64

In [15]:
new_data_frame["Extra"] = 10

In [16]:
new_data_frame

             Age    Salary  Seniority  Extra
Serkan -1.175653  1.259859   1.336775     10
Ahmet  -0.712035  0.657909   0.384306     10
Mısra  -1.774175  1.787384   0.391065     10
İpek   -1.402569  0.432498  -0.624458     10

In [17]:
new_data_frame.drop("Extra", axis = 1 )

             Age    Salary  Seniority
Serkan -1.175653  1.259859   1.336775
Ahmet  -0.712035  0.657909   0.384306
Mısra  -1.774175  1.787384   0.391065
İpek   -1.402569  0.432498  -0.624458

In [18]:
new_data_frame

             Age    Salary  Seniority  Extra
Serkan -1.175653  1.259859   1.336775     10
Ahmet  -0.712035  0.657909   0.384306     10
Mısra  -1.774175  1.787384   0.391065     10
İpek   -1.402569  0.432498  -0.624458     10

In [19]:
new_data_frame.drop("Extra", axis=1, inplace=True)

In [20]:
new_data_frame

             Age    Salary  Seniority
Serkan -1.175653  1.259859   1.336775
Ahmet  -0.712035  0.657909   0.384306
Mısra  -1.774175  1.787384   0.391065
İpek   -1.402569  0.432498  -0.624458

In [21]:
new_data_frame.drop("Ahmet")

             Age    Salary  Seniority
Serkan -1.175653  1.259859   1.336775
Mısra  -1.774175  1.787384   0.391065
İpek   -1.402569  0.432498  -0.624458

In [22]:
new_data_frame["Mısra"] = 10

In [23]:
new_data_frame

             Age    Salary  Seniority  Mısra
Serkan -1.175653  1.259859   1.336775     10
Ahmet  -0.712035  0.657909   0.384306     10
Mısra  -1.774175  1.787384   0.391065     10
İpek   -1.402569  0.432498  -0.624458     10

In [24]:
new_data_frame.drop("Mısra")

             Age    Salary  Seniority  Mısra
Serkan -1.175653  1.259859   1.336775     10
Ahmet  -0.712035  0.657909   0.384306     10
İpek   -1.402569  0.432498  -0.624458     10

In [25]:
new_data_frame.drop("Mısra", axis=1, inplace=True)

In [26]:
new_data_frame

             Age    Salary  Seniority
Serkan -1.175653  1.259859   1.336775
Ahmet  -0.712035  0.657909   0.384306
Mısra  -1.774175  1.787384   0.391065
İpek   -1.402569  0.432498  -0.624458

In [27]:
new_data_frame.loc["İpek"]

Age         -1.402569
Salary       0.432498
Seniority   -0.624458
Name: İpek, dtype: float64

In [28]:
new_data_frame.loc["İpek"]["Salary"]

np.float64(0.4324979850733336)

In [29]:
new_data_frame.loc["İpek","Salary"]

np.float64(0.4324979850733336)

In [30]:
new_data_frame.loc["İpek","Salary"] = 10

In [31]:
new_data_frame

             Age     Salary  Seniority
Serkan -1.175653   1.259859   1.336775
Ahmet  -0.712035   0.657909   0.384306
Mısra  -1.774175   1.787384   0.391065
İpek   -1.402569  10.000000  -0.624458

In [32]:
new_data_frame > 0

          Age  Salary  Seniority
Serkan  False    True       True
Ahmet   False    True       True
Mısra   False    True       True
İpek    False    True      False

In [33]:
boolean_frame = new_data_frame > 0

In [34]:
new_data_frame[boolean_frame]

        Age     Salary  Seniority
Serkan  NaN   1.259859   1.336775
Ahmet   NaN   0.657909   0.384306
Mısra   NaN   1.787384   0.391065
İpek    NaN  10.000000        NaN

In [35]:
new_data_frame[new_data_frame > 0]

        Age     Salary  Seniority
Serkan  NaN   1.259859   1.336775
Ahmet   NaN   0.657909   0.384306
Mısra   NaN   1.787384   0.391065
İpek    NaN  10.000000        NaN

In [36]:
new_data_frame

             Age     Salary  Seniority
Serkan -1.175653   1.259859   1.336775
Ahmet  -0.712035   0.657909   0.384306
Mısra  -1.774175   1.787384   0.391065
İpek   -1.402569  10.000000  -0.624458

In [37]:
new_data_frame[new_data_frame["Salary"] > 1]

             Age     Salary  Seniority
Serkan -1.175653   1.259859   1.336775
Mısra  -1.774175   1.787384   0.391065
İpek   -1.402569  10.000000  -0.624458

In [38]:
new_data_frame

             Age     Salary  Seniority
Serkan -1.175653   1.259859   1.336775
Ahmet  -0.712035   0.657909   0.384306
Mısra  -1.774175   1.787384   0.391065
İpek   -1.402569  10.000000  -0.624458

In [39]:
new_data_frame.reset_index()

    index       Age     Salary  Seniority
0  Serkan -1.175653   1.259859   1.336775
1   Ahmet -0.712035   0.657909   0.384306
2   Mısra -1.774175   1.787384   0.391065
3    İpek -1.402569  10.000000  -0.624458

In [40]:
reset_frame = new_data_frame.reset_index()

In [41]:
reset_frame

    index       Age     Salary  Seniority
0  Serkan -1.175653   1.259859   1.336775
1   Ahmet -0.712035   0.657909   0.384306
2   Mısra -1.774175   1.787384   0.391065
3    İpek -1.402569  10.000000  -0.624458

In [42]:
new_data_frame

             Age     Salary  Seniority
Serkan -1.175653   1.259859   1.336775
Ahmet  -0.712035   0.657909   0.384306
Mısra  -1.774175   1.787384   0.391065
İpek   -1.402569  10.000000  -0.624458

In [43]:
reset_frame.loc[0]

index          Serkan
Age         -1.175653
Salary       1.259859
Seniority    1.336775
Name: 0, dtype: object

In [44]:
new_indices = ["Srkn", "Ahmt", "Msr", "İpk"]

In [45]:
new_data_frame["New_İndex"] = new_indices

In [46]:
new_data_frame

             Age     Salary  Seniority New_İndex
Serkan -1.175653   1.259859   1.336775      Srkn
Ahmet  -0.712035   0.657909   0.384306      Ahmt
Mısra  -1.774175   1.787384   0.391065       Msr
İpek   -1.402569  10.000000  -0.624458       İpk

In [47]:
new_data_frame.set_index("New_İndex", inplace=True)

In [48]:
new_data_frame

                Age     Salary  Seniority
New_İndex
Srkn      -1.175653   1.259859   1.336775
Ahmt      -0.712035   0.657909   0.384306
Msr       -1.774175   1.787384   0.391065
İpk       -1.402569  10.000000  -0.624458

In [49]:
new_data_frame.loc["Msr"]

Age         -1.774175
Salary       1.787384
Seniority    0.391065
Name: Msr, dtype: float64

In [50]:
# Multi İndex

In [51]:
first_index = ["Simpson", "Simpson", "Simpson", "South Park", "South Park", "South Park"]

In [52]:
inner_index = ["Homer", "Bart", "Marge", "Cartman", "Kenny", "Kyle"]

In [53]:
zipped_index = list(zip(first_index,inner_index))

In [54]:
zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [55]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)

In [56]:
zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [57]:
sample_values = np.ones((6,2))

In [58]:
big_df = pd.DataFrame(sample_values, index = zipped_index, columns = ["Age", "Salary"])

In [59]:
big_df

                    Age  Salary
Simpson    Homer    1.0     1.0
           Bart     1.0     1.0
           Marge    1.0     1.0
South Park Cartman  1.0     1.0
           Kenny    1.0     1.0
           Kyle     1.0     1.0

In [60]:
big_df["Age"]

Simpson     Homer      1.0
            Bart       1.0
            Marge      1.0
South Park  Cartman    1.0
            Kenny      1.0
            Kyle       1.0
Name: Age, dtype: float64

In [61]:
big_df.loc["Simpson"]

       Age  Salary
Homer  1.0     1.0
Bart   1.0     1.0
Marge  1.0     1.0

In [62]:
big_df.loc["Simpson"].loc["Homer"]

Age       1.0
Salary    1.0
Name: Homer, dtype: float64